### ISSUE TITLE
Green is not green on hue play bars

### ISSUE THREAD

**Issue by Atsmusic** [TUnbehaun/phue-racing-flags#10]
The green flag is not green at my hue play bars it's more of a yellow, even if I put the rgb values on 0 255 0.

**Comment by TUnbehaun** [comment]
Hi @Atsmusic,

this should not be a problem with the app, but much rather with the Play Bars themselves. I experienced similiar problems with different Hue lights even when using the official Philips Hue app and setting the color to green there. Some lights really have a problem to display a proper green and have more of a yellow tint, as you described. You can try and counter it a bit by going more to the green-blueish side, but you probably won't achieve a perfect green.

**Comment by zhunterzz** [comment]
Wanted to comment that this is still happening. The main issue is green. I can get my Hue hardware to give me a full green, but when I put in 255 for green only, I get a weird yellowish green. No problem getting full green in the hue app. Must be with how its communicating the parameters for displaying green. Must be a way to resolve this.  Love the app regardless, but its frustrating when I see a yellow flag and realize its actually trying to show me green.
