### ISSUE TITLE
remove global execution

### ISSUE THREAD

**Issue by a-tal** [TUnbehaun/phue-racing-flags#5]
use

```python
if __name__ == "__main__":
```

before this line:

https://github.com/TUnbehaun/phue-racing-flags/blob/cacee68ea9b111d1000afbce312e4523c380b0e2/gui.py#L516

[then you can look into packaging maybe and use the same function as an entrypoint]

otherwise nice project, great idea!

**Comment by TUnbehaun** [comment]
Removed the global execution and will have a look at packaging. Thanks a lot for your feedback!
