### ISSUE TITLE
Add a "sync on startup" checkbox.

### ISSUE THREAD

**Issue by Xantrass** [TUnbehaun/phue-racing-flags#8]
Hey, 
it would be really cool if you could add an option that the app starts live sync directly after startup.

I use iRacing Manger to autmatically start all necessary apps when iracing launches, and so far phue-racing-flags is the only app that needs an addional click to start working.
If it is configured before, the app stores all necessary information to work properly, so a "start sync automatically" should be possible.

Thank you very much for your effort :)

Best Regards.

**Comment by TUnbehaun** [comment]
Hey,

sounds like an awesome idea! Will definitely implement this in the near future.

Thank you for your input!

Best Regards.

**Comment by TUnbehaun** [comment]
Added in v0.0.7-release.0
