### ISSUE TITLE
Setting Light actions

### ISSUE THREAD

**Issue by RacerKris23** [TUnbehaun/phue-racing-flags#9]
How do I change the actions the lights take when a flag is displayed? Currently the light blinks once or stays static when the flag is displayed. I would like to find out how to change the yellow flag for example. Id like it to flash yellow during the duration the flag is shown. Same with the green flag.

**Comment by TUnbehaun** [comment]
Currently the app only supports static lighting. But enabling flashing lights is planned for a future update.
